apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: podkrepibg-dev

resources:
 - keycloak-config.yaml
 - sendgrid-config.yaml
 - sentry-config.yaml
 - service.yaml
 - deployment.yaml
