name: API tests

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'
    branches: [master]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [master]

jobs:
  run-tests:
    name: Run API tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Run database
        run: docker-compose up -d pg-db
      - run: yarn
      - name: Generate Prisma DB client
        run: yarn prisma generate
      - name: Migrate database
        run: yarn prisma migrate deploy
      - name: NX Build and lint API # https://github.com/marketplace/actions/nrwl-nx
        uses: MansaGroup/nrwl-nx-action@v2
        with:
          targets: lint,build
          projects: api
      - name: Jest coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2.0.5
        with:
          package-manager: yarn
          test-script: yarn test:ci
